package com.happyclaw.hikinghappy.data.export

import com.happyclaw.hikinghappy.data.local.entity.TrackPoint
import com.happyclaw.hikinghappy.data.local.entity.TrackSession
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object KmlExporter {

    fun generate(session: TrackSession, points: List<TrackPoint>): String {
        val sdf = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault())
        val coordString = points.joinToString("\n") { point ->
            "${point.longitude},${point.latitude},${point.altitude}"
        }

        val startTime = sdf.format(Date(session.startTime))
        val endTime = session.endTime?.let { sdf.format(Date(it)) } ?: startTime
        val name = buildString {
            append(session.activityType.displayName())
            session.location?.let {
                if (it.isNotBlank()) append(" - $it")
            }
        }

        return """<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>$name</name>
    <description>
Generated by HikingHappy
Distance: ${"%.2f".format(session.totalDistance)}m
Duration: ${formatDuration(session.totalDuration)}
Max Altitude: ${"%.1f".format(session.maxAltitude)}m
    </description>
    <TimeSpan>
      <begin>$startTime</begin>
      <end>$endTime</end>
    </TimeSpan>
    <Style id="trackStyle">
      <LineStyle>
        <color>ff2d9c4f</color>
        <width>3</width>
      </LineStyle>
    </Style>
    <Placemark>
      <name>$name</name>
      <styleUrl>#trackStyle</styleUrl>
      <LineString>
        <coordinates>
$coordString
        </coordinates>
      </LineString>
    </Placemark>
  </Document>
</kml>""".trimIndent()
    }

    fun fileName(session: TrackSession): String {
        val date = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault())
            .format(Date(session.startTime))
        return "HikingHappy_${session.activityType.name}_$date.kml"
    }

    private fun formatDuration(seconds: Long): String {
        val h = seconds / 3600
        val m = (seconds % 3600) / 60
        val s = seconds % 60
        return if (h > 0) "%dh %02dm %02ds".format(h, m, s)
        else "%02dm %02ds".format(m, s)
    }
}
